/**
 * DUST//SIGNAL — Site content registry.
 * Brief §29: README must describe routes and systems.
 * Brief §6: Original symbol system.
 * Brief §5: Brand identity.
 */

export const SITE = {
  name: "DUST//SIGNAL",
  statement: "Probability has a pulse.",
  supporting:
    "A computational observatory studying motion, uncertainty, and rhythm.",
  version: "1.0.0",
  buildYear: 2026,
  fieldCode: "DSF-00",
} as const;

export interface RouteMeta {
  path: string;
  code: string;
  label: string;
  title: string;
  subtitle: string;
  description: string;
}

export const ROUTES: RouteMeta[] = [
  {
    path: "/",
    code: "00",
    label: "OBSERVATORY",
    title: "The Observatory",
    subtitle: "Entry field",
    description:
      "A computational observatory studying uncertainty through mathematics, sound, and motion.",
  },
  {
    path: "/models",
    code: "01",
    label: "MODELS",
    title: "Mathematical Fields",
    subtitle: "Modular laboratory",
    description:
      "Interactive mathematical models — stochastic drift, volatility surfaces, covariance bodies, and Fourier rooms.",
  },
  {
    path: "/signal",
    code: "02",
    label: "SIGNAL",
    title: "Audio-Visual Sequencer",
    subtitle: "Procedural house rhythm",
    description:
      "A 16-step / 4-channel procedural house-music visual sequencer. Sound is generated live by the Web Audio API.",
  },
  {
    path: "/archive",
    code: "03",
    label: "ARCHIVE",
    title: "Experiments",
    subtitle: "Curated field record",
    description:
      "Six original experiments translating quantitative systems into spatial form.",
  },
  {
    path: "/protocol",
    code: "04",
    label: "PROTOCOL",
    title: "Philosophy and Method",
    subtitle: "Editorial statement",
    description:
      "The thinking behind DUST//SIGNAL — observation, uncertainty, rhythm, and translation.",
  },
];

export interface Force {
  code: string;
  name: string;
  tagline: string;
  description: string;
  visualSystem: string[];
  color: string;
}

export const FOUR_FORCES: Force[] = [
  {
    code: "01",
    name: "DRIFT",
    tagline: "Uncertainty expressed as motion.",
    description:
      "Geometric Brownian motion generated by thousands of seeded paths. Paths separate and converge over time, producing a living field of possible trajectories.",
    visualSystem: [
      "Geometric Brownian motion",
      "Thousands of seeded paths",
      "Paths separating and converging over time",
    ],
    color: "#D89A48",
  },
  {
    code: "02",
    name: "PHASE",
    tagline: "Oscillation expressed as structure.",
    description:
      "Sine waves with phase offsets compose Lissajous forms and interference patterns. Frequency relationships become spatial geometry.",
    visualSystem: [
      "Sine waves",
      "Phase offsets",
      "Lissajous forms",
      "Interference patterns",
    ],
    color: "#D8C7A9",
  },
  {
    code: "03",
    name: "PRESSURE",
    tagline: "Density expressed as terrain.",
    description:
      "Volatility values deform a procedural surface, producing peaks, valleys, stress zones, and flattening regions.",
    visualSystem: [
      "Volatility values deforming a surface",
      "Peaks, valleys, stress zones, and flattening",
    ],
    color: "#A46C3B",
  },
  {
    code: "04",
    name: "RHYTHM",
    tagline: "Time expressed as repetition.",
    description:
      "A 16-step grid arranges pulses, gates, rests, accents, and releases. Repetition establishes the system; variation reveals it.",
    visualSystem: [
      "16-step sequencing",
      "Pulses, gates, rests, accents, and releases",
    ],
    color: "#A43124",
  },
];

export interface Experiment {
  number: string;
  slug: string;
  title: string;
  hypothesis: string;
  mathematicalBasis: string;
  formula: string;
  visualSystem: string;
  interaction: string;
  year: number;
  seed: number;
  status: "live" | "archival" | "experimental";
}

export const EXPERIMENTS: Experiment[] = [
  {
    number: "01",
    slug: "volatility-field",
    title: "VOLATILITY FIELD",
    hypothesis:
      "Uncertainty has topography. A surface deformed by volatility values reveals where pressure concentrates.",
    mathematicalBasis:
      "Synthetic SVI-style implied volatility parametrisation across log-moneyness and time-to-expiry.",
    formula: "σ²(k, τ) = a + b · {ρ·k + √(k² + σ_sl²)}",
    visualSystem: "Three-dimensional deformed terrain mesh, hue-mapped by σ magnitude.",
    interaction: "Rotate, zoom, slice cross-sections, toggle wireframe.",
    year: 2026,
    seed: 0x4d535f47,
    status: "live",
  },
  {
    number: "02",
    slug: "covariance-body",
    title: "COVARIANCE BODY",
    hypothesis:
      "Relationships have geometry. A correlation matrix maps onto a spatial network whose structure is the data itself.",
    mathematicalBasis:
      "PSD covariance via A·Aᵀ construction, normalised to correlation coefficients.",
    formula: "ρ_ij = C_ij / (σ_i · σ_j)",
    visualSystem: "Network of nodes connected by signed, weighted edges.",
    interaction: "Drag to rotate, click nodes to isolate, adjust sparsity.",
    year: 2026,
    seed: 0x43304231,
    status: "live",
  },
  {
    number: "03",
    slug: "fourier-room",
    title: "FOURIER ROOM",
    hypothesis:
      "A room can be assembled from frequencies. Summing sine waves produces space.",
    mathematicalBasis: "Trigonometric Fourier series composition.",
    formula: "f(t) = Σ Aₙ · sin(2π fₙ t + φₙ)",
    visualSystem: "Stacked wave components, combined waveform, circular phase diagram.",
    interaction: "Add/remove components, adjust frequency, amplitude, and phase.",
    year: 2026,
    seed: 0x46523432,
    status: "live",
  },
  {
    number: "04",
    slug: "brownian-choir",
    title: "BROWNIAN CHOIR",
    hypothesis:
      "Many voices singing the same stochastic process produce a chorus of possibility.",
    mathematicalBasis:
      "Geometric Brownian motion dS = μSdt + σSdW, ensemble statistics over thousands of paths.",
    formula: "dS = μSdt + σSdW",
    visualSystem: "Thousands of seeded paths drifting through depth.",
    interaction: "Adjust drift, volatility, time horizon, regenerate seeds.",
    year: 2026,
    seed: 0x42434830,
    status: "live",
  },
  {
    number: "05",
    slug: "phase-architecture",
    title: "PHASE ARCHITECTURE",
    hypothesis:
      "Phase relationships build structures that single frequencies cannot.",
    mathematicalBasis: "Lissajous parametric curves and beat interference.",
    formula: "x = sin(2π f₁ t + φ),  y = sin(2π f₂ t)",
    visualSystem: "Parametric Lissajous curves, evolving interference fields.",
    interaction: "Tune frequency ratios, sweep phase, observe topology changes.",
    year: 2026,
    seed: 0x50483134,
    status: "experimental",
  },
  {
    number: "06",
    slug: "liquidity-horizon",
    title: "LIQUIDITY HORIZON",
    hypothesis:
      "Density in time creates a horizon. Where activity concentrates, the horizon rises.",
    mathematicalBasis:
      "Kernel density estimation over simulated event arrival times.",
    formula: "f̂(t) = (1/nh) Σ K((t − t_i)/h)",
    visualSystem: "Ridgeline of density curves receding toward a horizon line.",
    interaction: "Adjust kernel bandwidth, regenerate event stream.",
    year: 2026,
    seed: 0x4c483030,
    status: "experimental",
  },
];

export interface ProtocolSection {
  id: string;
  label: string;
  heading: string;
  body: string;
}

export const PROTOCOL_SECTIONS: ProtocolSection[] = [
  {
    id: "observation",
    label: "01 / OBSERVATION",
    heading: "Observation",
    body:
      "A model reduces the world so that one behaviour can be examined more closely. Every reduction reveals something and removes something. The observatory exists not to capture the world entire, but to isolate the parts of it that move — and to ask why.",
  },
  {
    id: "uncertainty",
    label: "02 / UNCERTAINTY",
    heading: "Uncertainty",
    body:
      "Uncertainty is not visual noise. It has distribution, direction, memory, and scale. To treat it as decoration is to flatten the very thing the observatory was built to study. Here, randomness is given a structure — a shape, a velocity, a horizon — and allowed to speak.",
  },
  {
    id: "rhythm",
    label: "03 / RHYTHM",
    heading: "Rhythm",
    body:
      "Rhythm is a method of organising expectation. Repetition establishes a system. Variation makes the system visible. The four-beat cycle returns to the same position without returning to the same moment — and that small asymmetry is where listening begins.",
  },
  {
    id: "translation",
    label: "04 / TRANSLATION",
    heading: "Translation",
    body:
      "DUST//SIGNAL translates equations into movement without pretending that the image is the equation itself. The mathematics remains the source. The visual field is one possible reading of it — neither authoritative nor decorative, but a careful re-statement in another medium.",
  },
];

export const PROTOCOL_PRINCIPLES: string[] = [
  "Show the system.",
  "Preserve uncertainty.",
  "Use restraint.",
  "Let interaction reveal structure.",
  "Never confuse spectacle with meaning.",
  "Make every number accountable.",
  "Allow silence.",
  "Protect performance.",
  "Build original work.",
];

export const FOUR_FORCES_COPY = [
  "Markets move.",
  "Particles drift.",
  "Bodies repeat.",
  "Rooms resonate.",
  "Nothing remains still.",
];

export const DISCLAIMER =
  "This is a visual probability experiment, not financial guidance. All data is synthetic.";
